# Database
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todolist
    driver-class-name: org.h2.Driver
    username: sa
    password:
# JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

# Log
logging:
  level:
    org.hibernate.SQL: debug

